environment:
  matrix:
    - TARGET: i686-pc-windows-gnu
      RUST_VERSION: 1.31.0
      BITS: 32
    - TARGET: x86_64-pc-windows-gnu
      RUST_VERSION: 1.31.0
      BITS: 64
install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-${env:RUST_VERSION}-${env:TARGET}.exe"
  - rust-%RUST_VERSION%-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Rust"
  - SET PATH=C:\Rust\bin
  - SET PATH=C:\msys64\mingw%BITS%\bin;C:\msys64\usr\bin;%PATH%
  - echo %PATH%
  - gcc --version
  - rustc -V
  - cargo -V

build_script:
    - cargo build --verbose

test_script:
    - cargo test --verbose

